"""LLM Detector — Signal 2 of the Provenance Guard detection pipeline.

Asks a Groq-hosted model to judge whether a piece of creative writing was written
by a human or generated by an AI and passed off as human work, returning a
calibrated probability `p_ai` and a short rationale. Reads `GROQ_API_KEY` (and an
optional `GROQ_MODEL`) from the environment.

The network call is wrapped so that any failure — missing key, timeout, an
unparseable response, an unknown model — degrades gracefully to a neutral result
with zero reliability. The aggregator then simply falls back to the stylometric
signal instead of the endpoint erroring out.
"""

from __future__ import annotations

import json
import math
import os

from dotenv import load_dotenv

load_dotenv()

VERSION = "llm-detector-v1"
# Configurable so the model can be swapped without code changes. The default is a
# current Groq production model; set GROQ_MODEL to override.
DEFAULT_MODEL = os.environ.get("GROQ_MODEL", "llama-3.3-70b-versatile")

_SYSTEM_PROMPT = (
    "You are a forensic linguist assessing whether a piece of creative writing was "
    "written by a human or generated by an AI language model and passed off as human "
    "work.\n\n"
    "Judge only from internal evidence: voice, idiosyncrasy, specificity, emotional "
    "texture, surprising word choices, and structural rhythm. Human creative writing "
    "tends to be idiosyncratic, uneven, and specific; AI text tends to be fluent, even, "
    "generic, and safe — but this is a tendency, not a rule, and skilled humans and "
    "lightly edited AI can each look like the other.\n\n"
    "Return a calibrated probability, not a verdict. Use the full 0-1 range and reserve "
    "values near 0 or 1 for cases with strong evidence. When the text is short or the "
    "evidence is genuinely ambiguous, stay near 0.5.\n\n"
    'Respond ONLY with a JSON object of the form '
    '{"p_ai": <float between 0 and 1>, "rationale": "<one or two sentences>"} '
    "where p_ai is your probability that the text was AI-generated."
)

_USER_TEMPLATE = 'Assess the following text:\n\n"""\n{text}\n"""'


def _length_reliability(text: str) -> float:
    """Even a strong model needs enough text; saturate around a few hundred chars."""
    return 1.0 - math.exp(-len(text) / 300.0)


def analyze(text: str, model: str | None = None, timeout: float = 20.0) -> dict:
    """Estimate p(AI-generated) for `text` via a Groq LLM.

    Returns a dict with `p_ai`, `reliability`, `rationale`, `model`, `version`.
    On any failure the result is neutral (`p_ai` 0.5) with `reliability` 0.0 so the
    aggregator ignores it.
    """
    model = model or DEFAULT_MODEL
    api_key = os.environ.get("GROQ_API_KEY")

    result = {
        "p_ai": 0.5,
        "reliability": 0.0,
        "rationale": None,
        "model": model,
        "version": VERSION,
    }

    if not api_key:
        result["rationale"] = "LLM signal unavailable: GROQ_API_KEY not set."
        return result

    try:
        from groq import Groq

        client = Groq(api_key=api_key, timeout=timeout)
        completion = client.chat.completions.create(
            model=model,
            messages=[
                {"role": "system", "content": _SYSTEM_PROMPT},
                {"role": "user", "content": _USER_TEMPLATE.format(text=text)},
            ],
            temperature=0.0,
            max_tokens=300,
            response_format={"type": "json_object"},
        )
        parsed = json.loads(completion.choices[0].message.content)
        p_raw = float(parsed["p_ai"])
        rationale = parsed.get("rationale")
    except Exception as exc:  # network / parse / key / model errors → graceful neutral
        result["rationale"] = f"LLM signal unavailable: {type(exc).__name__}: {exc}"
        return result

    # Calibration: clamp out impossible certainty and shrink slightly toward 0.5,
    # since LLM self-reported probabilities tend to be overconfident.
    p_clamped = max(0.0, min(1.0, p_raw))
    p_cal = 0.5 + (p_clamped - 0.5) * 0.9
    p_cal = max(0.02, min(0.98, p_cal))

    result["p_ai"] = round(p_cal, 4)
    result["reliability"] = round(0.85 * _length_reliability(text), 4)
    result["rationale"] = rationale
    return result
